export { Tabs, type TabsProps } from './tabs'
export { TabsContent, type TabsContentProps } from './tabs-content'
export { TabsList, type TabsListProps } from './tabs-list'
export { TabsTrigger, type TabsTriggerProps } from './tabs-trigger'
export { TabsActivationMode } from './types'
