export const componentNavLinks = [
  { to: '/components/spinner', label: 'Spinner' },
  { to: '/components/button', label: 'Button' },
  { to: '/components/input', label: 'Input' },
  { to: '/components/textarea', label: 'Textarea' },
  { to: '/components/switch', label: 'Switch' },
  { to: '/components/checkbox', label: 'Checkbox' },
  { to: '/components/badge', label: 'Badge' },
  { to: '/components/alert', label: 'Alert' },
  { to: '/components/avatar', label: 'Avatar' },
  { to: '/components/card', label: 'Card' },
  { to: '/components/skeleton', label: 'Skeleton' },
  { to: '/components/dialog', label: 'Dialog' },
  { to: '/components/dropdown-menu', label: 'Dropdown Menu' },
  { to: '/components/select', label: 'Select' },
  { to: '/components/tooltip', label: 'Tooltip' },
  { to: '/components/tabs', label: 'Tabs' },
  { to: '/components/form', label: 'Form' },
  { to: '/components/radio-group', label: 'Radio Group' },
  { to: '/components/table', label: 'Table' },
  { to: '/components/accordion', label: 'Accordion' },
  { to: '/components/avatar-group', label: 'Avatar Group' },
  { to: '/components/separator', label: 'Separator' },
  { to: '/components/calendar', label: 'Calendar' },
  { to: '/components/date-picker', label: 'Date Picker' },
  { to: '/components/combobox', label: 'Combobox' },
  { to: '/components/number-field', label: 'Number Field' },
  { to: '/components/toggle-group', label: 'Toggle Group' },
  { to: '/components/progress', label: 'Progress' },
  { to: '/components/stepper', label: 'Stepper' },
  { to: '/components/notice', label: 'Notice' },
  { to: '/components/empty-state', label: 'Empty State' },
  { to: '/components/sidebar', label: 'Sidebar' },
  { to: '/components/carousel', label: 'Carousel' },
  { to: '/components/timeline', label: 'Timeline' },
  { to: '/components/drawer', label: 'Drawer' },
  { to: '/components/breadcrumb', label: 'Breadcrumb' },
  { to: '/components/pagination', label: 'Pagination' },
  { to: '/components/link', label: 'Link' },
] as const
