/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsRouteRouteImport } from './routes/components/route'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as ComponentsInputRouteImport } from './routes/components/input'
import { Route as ComponentsSkeletonRouteImport } from './routes/components/skeleton'
import { Route as ComponentsSpinnerRouteImport } from './routes/components/spinner'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRouteRoute = ComponentsRouteRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsInputRoute = ComponentsInputRouteImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsSkeletonRoute = ComponentsSkeletonRouteImport.update({
  id: '/skeleton',
  path: '/skeleton',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsSpinnerRoute = ComponentsSpinnerRouteImport.update({
  id: '/spinner',
  path: '/spinner',
  getParentRoute: () => ComponentsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRouteRouteWithChildren
  '/components/input': typeof ComponentsInputRoute
  '/components/skeleton': typeof ComponentsSkeletonRoute
  '/components/spinner': typeof ComponentsSpinnerRoute
  '/components/': typeof ComponentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/skeleton': typeof ComponentsSkeletonRoute
  '/components/spinner': typeof ComponentsSpinnerRoute
  '/components': typeof ComponentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components': typeof ComponentsRouteRouteWithChildren
  '/components/input': typeof ComponentsInputRoute
  '/components/skeleton': typeof ComponentsSkeletonRoute
  '/components/spinner': typeof ComponentsSpinnerRoute
  '/components/': typeof ComponentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components'
    | '/components/input'
    | '/components/skeleton'
    | '/components/spinner'
    | '/components/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components/input'
    | '/components/skeleton'
    | '/components/spinner'
    | '/components'
  id:
    | '__root__'
    | '/'
    | '/components'
    | '/components/input'
    | '/components/skeleton'
    | '/components/spinner'
    | '/components/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsRouteRoute: typeof ComponentsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/input': {
      id: '/components/input'
      path: '/input'
      fullPath: '/components/input'
      preLoaderRoute: typeof ComponentsInputRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/skeleton': {
      id: '/components/skeleton'
      path: '/skeleton'
      fullPath: '/components/skeleton'
      preLoaderRoute: typeof ComponentsSkeletonRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/spinner': {
      id: '/components/spinner'
      path: '/spinner'
      fullPath: '/components/spinner'
      preLoaderRoute: typeof ComponentsSpinnerRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
  }
}

interface ComponentsRouteRouteChildren {
  ComponentsInputRoute: typeof ComponentsInputRoute
  ComponentsSkeletonRoute: typeof ComponentsSkeletonRoute
  ComponentsSpinnerRoute: typeof ComponentsSpinnerRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
}

const ComponentsRouteRouteChildren: ComponentsRouteRouteChildren = {
  ComponentsInputRoute: ComponentsInputRoute,
  ComponentsSkeletonRoute: ComponentsSkeletonRoute,
  ComponentsSpinnerRoute: ComponentsSpinnerRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
}

const ComponentsRouteRouteWithChildren = ComponentsRouteRoute._addFileChildren(
  ComponentsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsRouteRoute: ComponentsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
